# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "StefanScherer/windows_10"
  config.vm.hostname = "w10-emm"
  config.vm.network "private_network" , ip: "172.16.0.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2 
  end
end
  
