# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "StefanScherer/windows_2019"
  config.vm.hostname = "server-emm"
  config.vm.network "private_network" , ip: "172.16.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end
end
